### PR TITLE
8315896: Perspective lod tests fail because of minute difference in values

### PR DESCRIPTION
**Pull request by jayathirthrao**
Two perspective lod tests fail because of minute differences in expected values.

Failing tests:
test/scenegraph/fx3d/lod/PerspectiveLodCameraTest.java:
test/scenegraph/fx3d/lod/PerspectiveLodGroupTest.java: 

Exception:
test test.scenegraph.fx3d.lod.LodTests.sphereInitialLightOnTest(): failure
org.jemmy.TimeoutExpiredException: State 'Expected 50180.140882730484, but was 50180.137157440186' has not been reached in 1000 milliseconds
at org.jemmy.timing.Waiter.ensureValue(Waiter.java:93)
at test.scenegraph.fx3d.lod.LodTestBase.checkLod(LodTestBase.java:117)
at test.scenegraph.fx3d.lod.LodTests.sphereInitialLightOnTest(LodTests.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.lang.Thread.run(Thread.java:833) 

These little difference in values are seen both initial drawing and updates.
These tests are not run from long time and change in product might change lod values.

With updated lod values i have verified that both the tests pass in OpenGL and Metal pipeline with both retina display(scale = 2) and external monitor(scale = 1).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315896](https://bugs.openjdk.org/browse/JDK-8315896): Perspective lod tests fail because of minute difference in values (**Bug** - P4)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx-tests.git pull/6/head:pull/6` \
`$ git checkout pull/6`

Update a local copy of the PR: \
`$ git checkout pull/6` \
`$ git pull https://git.openjdk.org/jfx-tests.git pull/6/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 6`

View PR using the GUI difftool: \
`$ git pr show -t 6`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx-tests/pull/6.diff">https://git.openjdk.org/jfx-tests/pull/6.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx-tests/pull/6#issuecomment-1711190741)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Two questions:

1. Have you run this on Windows to ensure that the D3D pipeline also passes with this change?
2. It might be better to compare using a tolerance rather than relying on an exact value being computed in floating-point arithmetic.

**Comment by jayathirthrao** [comment]
> Two questions:
> 
>     1. Have you run this on Windows to ensure that the D3D pipeline also passes with this change?
> 
>     2. It might be better to compare using a tolerance rather than relying on an exact value being computed in floating-point arithmetic.

Thanks @kevinrushforth for your inputs.
I have added tolerance which is definitely better than using fixed value for lod.

I have tried running jfx-tests using cygwin as well as cmd in windows.
For cygwin i followed same approach as we follow for macOS but with different path separator. Also https://ant.apache.org/manual/running.html talks about not using cygwin path for ant -Dproperty and i used absolute path. With all these still ant is not able to find javafx.home and jemmy-v3.jars. But with same path pattern it is able to find jtreg.home.
For cmd, i added needed environment variables but there also i am not able to run the tests.

I think its better to handle making jfx-tests run in Windows as part of separate bug.
Current change without verification in D3D will help in atleast comparing functionality between OpenGL and Metal in macOS.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Please file a follow-up bug to get the tests running on Windows.

**Comment by jayathirthrao** [comment]
> Looks good. Please file a follow-up bug to get the tests running on Windows.

I have created follow-up issue https://bugs.openjdk.org/browse/JDK-8319329 for Windows.

**Pull request closed without merging**
